(()=>{'use strict';
const $=id=>document.getElementById(id),mount=$('game'),loading=$('loading');
function fail(t){if(loading){loading.textContent=t;loading.classList.remove('hidden')}}
function start(){if(!window.THREE){fail('The 3D engine could not load. Check your connection and refresh.');return}try{boot()}catch(e){console.error(e);fail('3D game failed to start. Refresh the page.')}}
if(!window.THREE){fail('Loading 3D engine…');const s=document.createElement('script');s.src='https://unpkg.com/three@0.160.0/build/three.min.js';s.onload=start;s.onerror=start;document.head.appendChild(s)}else start();
function boot(){
 if(!mount)throw Error('Missing game element');const T=THREE;let scene=new T.Scene(),camera=new T.PerspectiveCamera(50,innerWidth/innerHeight,.1,180),renderer=new T.WebGLRenderer({antialias:false,powerPreference:'high-performance'}),ray=new T.Raycaster(),mouse=new T.Vector2();
 scene.background=new T.Color(0x07111d);scene.fog=new T.Fog(0x07111d,48,105);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.domElement.style.touchAction='none';mount.replaceChildren(renderer.domElement);
 scene.add(new T.HemisphereLight(0xb8d7ff,0x172313,2.1));let sun=new T.DirectionalLight(0xffffff,2.7);sun.position.set(18,34,12);scene.add(sun);
 const MAP=24,H=MAP/2,TILE=2.5,PC=0x4da6ff,EC=0xef6262;let armies=[],selected=null,territory=4,gold=1000,food=800,science=0,drag=false,lx=0,ly=0,yaw=.15,pitch=.78,dist=34;
 const terrain=new T.Mesh(new T.PlaneGeometry(MAP*TILE,MAP*TILE),new T.MeshLambertMaterial({color:0x21452f}));terrain.rotation.x=-Math.PI/2;terrain.userData.ground=true;scene.add(terrain);
 let water=new T.Mesh(new T.PlaneGeometry(125,125),new T.MeshBasicMaterial({color:0x0a2335}));water.rotation.x=-Math.PI/2;water.position.y=-.22;scene.add(water);
 let grid=new T.GridHelper(MAP*TILE,MAP,0x557b62,0x365342);grid.position.y=.025;grid.material.transparent=true;grid.material.opacity=.48;scene.add(grid);let units=new T.Group(),cities=new T.Group();scene.add(units,cities);
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),pos=(x,z)=>new T.Vector3((x-H+.5)*TILE,0,(z-H+.5)*TILE);
 function ring(color){let r=new T.Mesh(new T.RingGeometry(.72,.9,24),new T.MeshBasicMaterial({color,transparent:true,opacity:.95,side:T.DoubleSide}));r.rotation.x=-Math.PI/2;r.position.y=.16;r.name='selection';r.visible=false;return r}
 function army(owner,x,z,count){let g=new T.Group();g.position.copy(pos(x,z));g.userData={owner,x,z,count};let b=new T.Mesh(new T.CylinderGeometry(.58,.72,.2,8),new T.MeshStandardMaterial({color:owner==='player'?PC:EC}));b.position.y=.2;b.userData.army=g;g.add(b);for(let i=0;i<Math.min(10,Math.max(3,Math.ceil(count/10)));i++){let u=new T.Mesh(new T.BoxGeometry(.24,.72,.24),new T.MeshStandardMaterial({color:owner==='player'?0xd9edff:0xffd7d7}));u.position.set(rand(-.42,.42),.57,rand(-.42,.42));u.userData.army=g;g.add(u)}let pole=new T.Mesh(new T.CylinderGeometry(.035,.035,.9,6),new T.MeshStandardMaterial({color:0xd5dde5}));pole.position.y=.85;pole.userData.army=g;g.add(pole);let f=new T.Mesh(new T.PlaneGeometry(.38,.24),new T.MeshBasicMaterial({color:owner==='player'?PC:EC,side:T.DoubleSide}));f.position.set(.18,1.05,0);f.userData.army=g;g.add(f);g.add(ring(owner==='player'?0x72c5ff:0xff7474));units.add(g);armies.push(g);return g}
 function city(owner,x,z){let g=new T.Group();g.position.copy(pos(x,z));let base=new T.Mesh(new T.BoxGeometry(1.7,.25,1.7),new T.MeshStandardMaterial({color:owner==='player'?0x315f8c:owner==='enemy'?0x6b3434:0x4e5966}));base.position.y=.13;g.add(base);for(let i=0;i<4;i++){let h=rand(.8,1.5),b=new T.Mesh(new T.BoxGeometry(.42,h,.42),new T.MeshStandardMaterial({color:owner==='player'?0x8fb9d8:owner==='enemy'?0xb97878:0xaeb7c0}));b.position.set(i%2?.48:-.48,h/2+.22,i<2?-.42:.42);g.add(b);let roof=new T.Mesh(new T.ConeGeometry(.31,.32,4),new T.MeshStandardMaterial({color:0x303945}));roof.position.set(b.position.x,h+.39,b.position.z);roof.rotation.y=Math.PI/4;g.add(roof)}cities.add(g)}
 city('player',3,19);army('player',4,18,80);army('player',6,19,55);city('enemy',19,4);army('enemy',18,5,75);army('enemy',20,6,50);army('enemy',17,3,40);city('neutral',11,11);
 function cam(){let h=Math.cos(pitch)*dist;camera.position.set(Math.sin(yaw)*h,Math.sin(pitch)*dist,Math.cos(yaw)*h);camera.lookAt(0,0,0)}
 function hud(){ $('gold').textContent=Math.floor(gold).toLocaleString();$('food').textContent=Math.floor(food).toLocaleString();$('science').textContent=Math.floor(science).toLocaleString();$('territory').textContent=territory;$('troops').textContent=armies.filter(a=>a.userData.owner==='player').reduce((s,a)=>s+a.userData.count,0).toLocaleString();$('selection').textContent=selected?`Selected army · ${selected.userData.count} troops · Position ${selected.userData.x+1}, ${selected.userData.z+1}`:'No army selected.'}
 function hits(e){let r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);return ray.intersectObjects(scene.children,true)}
 function choose(e){if(drag)return;for(let h of hits(e)){if(h.object.userData.army){let a=h.object.userData.army;if(a.userData.owner==='player'){if(selected){let r=selected.getObjectByName('selection');if(r)r.visible=false}selected=a;let r=a.getObjectByName('selection');if(r)r.visible=true;$('orders').textContent='Right-click an adjacent tile to move or an enemy army to attack.';hud()}return} }if(selected){let r=selected.getObjectByName('selection');if(r)r.visible=false}selected=null;hud()}
 function move(a,x,z){if(Math.abs(a.userData.x-x)+Math.abs(a.userData.z-z)!==1){$('orders').textContent='Move one tile at a time in this practice build.';return}if(armies.some(q=>q!==a&&q.userData.owner==='player'&&q.userData.x===x&&q.userData.z===z)){ $('orders').textContent='Another friendly army is already there.';return}let from=a.position.clone(),to=pos(x,z),t0=performance.now();function step(n){let t=clamp((n-t0)/420,0,1),e=t*t*(3-2*t);a.position.lerpVectors(from,to,e);a.position.y=Math.sin(e*Math.PI)*.18;if(t<1)requestAnimationFrame(step);else{a.position.y=0;a.userData.x=x;a.userData.z=z;$('orders').textContent='Army moved.';hud()}}requestAnimationFrame(step)}
 function combat(a,d){if(Math.abs(a.userData.x-d.userData.x)+Math.abs(a.userData.z-d.userData.z)!==1){$('orders').textContent='That enemy is too far away.';return}let p=a.userData.count,def=d.userData.count;a.userData.count=Math.max(0,p-Math.max(1,Math.floor(def*.22)));d.userData.count=Math.max(0,def-Math.max(1,Math.floor(p*.38)));if(d.userData.count===0&&a.userData.count>0){d.userData.owner='player';d.userData.count=Math.max(1,Math.floor(a.userData.count*.25));territory++;$('orders').textContent='Victory! Enemy army captured.'}else $('orders').textContent='Battle complete. Both armies took losses.';visual(a);visual(d);hud()}
 function visual(a){let c=a.userData.owner==='player'?PC:EC,b=a.children[0];b.material.color.set(c);let f=a.children.find(q=>q.geometry&&q.geometry.type==='PlaneGeometry');if(f)f.material.color.set(c);let r=a.getObjectByName('selection');if(r)r.material.color.set(a.userData.owner==='player'?0x72c5ff:0xff7474)}
 function context(e){e.preventDefault();if(!selected)return;for(let h of hits(e)){if(h.object.userData.army){let a=h.object.userData.army;if(a.userData.owner==='enemy')combat(selected,a);return}if(h.object.userData.ground){let x=clamp(Math.floor(h.point.x/TILE+H),0,MAP-1),z=clamp(Math.floor(h.point.z/TILE+H),0,MAP-1);move(selected,x,z);return}}}
 renderer.domElement.addEventListener('click',choose);renderer.domElement.addEventListener('contextmenu',context);
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===1||(e.button===0&&e.shiftKey)){drag=false;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)}});
 renderer.domElement.addEventListener('pointermove',e=>{if((e.buttons&4)||(e.buttons&1&&e.shiftKey)){let dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>3)drag=true;yaw-=dx*.006;pitch=clamp(pitch+dy*.004,.48,1.18);cam();lx=e.clientX;ly=e.clientY}});
 renderer.domElement.addEventListener('wheel',e=>{dist=clamp(dist+e.deltaY*.025,17,58);cam()},{passive:true});$('reset').onclick=()=>location.reload();$('split').onclick=()=>{if(!selected||selected.userData.count<20){$('orders').textContent='Select an army with at least 20 troops.';return}let half=Math.floor(selected.userData.count/2);selected.userData.count-=half;let x=clamp(selected.userData.x+1,0,MAP-1);if(!armies.some(a=>a.userData.x===x&&a.userData.z===selected.userData.z))army('player',x,selected.userData.z,half);hud()};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')location.reload()});cam();hud();loading.classList.add('hidden');let last=performance.now();function loop(n=performance.now()){requestAnimationFrame(loop);if(n-last>1000){last=n;gold+=18;food+=12;science+=2;armies.filter(a=>a.userData.owner==='player').forEach(a=>a.userData.count+=2);hud()}renderer.render(scene,camera)}loop()
}
})();