// Nation Wars 0.4 — Practice Game
(() => {
  'use strict';
  function boot() {
    const $=id=>document.getElementById(id);
    const el={map:$('map'),arena:$('arena'),status:$('status'),time:$('time'),territory:$('territory'),score:$('score'),gold:$('gold'),food:$('food'),science:$('science'),troops:$('troops'),cities:$('cities'),enemies:$('enemies'),selection:$('selectionText'),nation:$('nationName'),objective:$('objective'),objectiveSub:$('objectiveSub'),deploy:$('deploy'),deployValue:$('deployValue'),log:$('log'),toast:$('toast'),side:$('side'),pause:$('pauseBtn'),modal:$('modal')};
    const missing=Object.entries(el).filter(([,v])=>!v).map(([k])=>k); if(missing.length) throw new Error('Missing game elements: '+missing.join(', '));
    const state={active:true,paused:false,time:0,score:0,turn:0,size:12,selected:null,deployment:50,gold:100,food:80,science:0,cities:1,tiles:{},loop:null,zoom:1,cameraX:0,cameraY:0,dragging:false,dragX:0,dragY:0,startX:0,startY:0,buildMode:false};
    const COLORS={player:'linear-gradient(145deg,#168ed0,#1266a5)',bot:'linear-gradient(145deg,#b83d57,#7d263d)',neutral:'linear-gradient(145deg,#344d63,#223648)'};
    const key=(r,c)=>`${r}-${c}`, tile=id=>state.tiles[id], owned=o=>Object.keys(state.tiles).filter(id=>tile(id).owner===o), troopCount=(o='player')=>owned(o).reduce((n,id)=>n+tile(id).troops,0), formatTime=s=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
    function neighbors(id){const [r,c]=id.split('-').map(Number),off=r%2===0?[[0,-1],[0,1],[-1,-1],[-1,0],[1,-1],[1,0]]:[[0,-1],[0,1],[-1,0],[-1,1],[1,0],[1,1]];return off.map(([dr,dc])=>key(r+dr,c+dc)).filter(x=>tile(x));}
    const adjacent=(a,b)=>neighbors(a).includes(b);
    function setStatus(t,k=''){el.status.textContent=t;el.status.className=`status ${k}`;}
    function addLog(t){const d=document.createElement('div');d.textContent=`${formatTime(state.time)}  ${t}`;el.log.prepend(d);while(el.log.children.length>8)el.log.lastChild.remove();}
    function toast(t){el.toast.textContent=t;el.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove('show'),1700);}
    function createMap(){el.map.innerHTML='';state.tiles={};const s=state.size,w=58,g=6,step=w+g;el.map.style.width=`${s*step+20}px`;el.map.style.height=`${s*step+20}px`;for(let r=0;r<s;r++)for(let c=0;c<s;c++){const id=key(r,c),b=document.createElement('button');b.className='tile neutral';b.id=`tile-${id}`;b.type='button';b.style.width=`${w}px`;b.style.height=`${w}px`;b.style.left=`${c*step+(r%2?step/2:0)}px`;b.style.top=`${r*step}px`;b.addEventListener('click',()=>clickTile(id));el.map.appendChild(b);state.tiles[id]={owner:'neutral',troops:2+Math.floor(Math.random()*5),city:false};}}
    function setOwner(id,o,n){if(!tile(id))return;tile(id).owner=o;tile(id).troops=n;renderTile(id);}
    function setupNations(){['5-5','5-6','6-5','6-6'].forEach(id=>setOwner(id,'player',22));['1-1','1-10','10-1','10-10'].forEach((id,i)=>setOwner(id,'bot',18+i*3));tile('5-5').city=true;renderAll();addLog('Your capital has been established at 6,6.');}
    function renderTile(id){const t=tile(id),b=$(`tile-${id}`);if(!t||!b)return;b.className=`tile ${t.owner}${state.selected===id?' selected':''}${state.buildMode&&t.owner==='player'&&!t.city?' can-target':''}`;b.style.background=COLORS[t.owner];b.innerHTML=`<span class="tile-content"><span class="troops">${Math.floor(t.troops)}</span><span class="coord">${id.replace('-',',')}</span><span class="citymark">${t.city?'◆':''}</span></span>`;}
    function renderAll(){Object.keys(state.tiles).forEach(renderTile);}
    function commander(){try{return localStorage.getItem('nationWarsPlayer')||'Commander';}catch(_){return 'Commander';}}
    function update(){el.time.textContent=formatTime(state.time);el.score.textContent=Math.floor(state.score);el.gold.textContent=Math.floor(state.gold);el.food.textContent=Math.floor(state.food);el.science.textContent=Math.floor(state.science);el.territory.textContent=owned('player').length;el.troops.textContent=Math.floor(troopCount());el.cities.textContent=state.cities;el.enemies.textContent=owned('bot').length;el.nation.textContent=commander();el.deployValue.textContent=state.deployment;el.pause.textContent=state.paused?'Resume':'Pause';el.selection.textContent=state.selected?`${state.selected} · ${Math.floor(tile(state.selected).troops)} troops${tile(state.selected).city?' · City':''}`:'Select one of your territories.';const p=owned('player').length;el.objective.textContent=p>=80?'You control most of the map. Finish the war.':p>=20?'Your nation is expanding. Push toward enemy territory.':'Expand your borders and defeat the rival nations.';el.objectiveSub.textContent=`${p} territories controlled · ${owned('bot').length} enemy territories remain.`;}
    function clickTile(id){if(!state.active||state.paused)return;const t=tile(id);if(!t)return;if(state.buildMode){if(t.owner!=='player'||t.city)return toast('Choose an empty territory you control.');if(state.gold<40)return toast('You need 40 gold to build.');t.city=true;state.gold-=40;state.cities++;state.score+=75;state.buildMode=false;addLog(`Built a city at ${id}.`);setStatus('City established.','good');renderAll();update();return;}if(!state.selected){if(t.owner==='player'){state.selected=id;renderAll();update();setStatus(`Selected ${id}. Choose an adjacent territory.`);}return;}if(id===state.selected){state.selected=null;renderAll();update();return;}if(!adjacent(state.selected,id)){toast('Choose an adjacent territory.');setStatus('That territory is not adjacent.');return;}const from=state.selected,amount=Math.max(1,Math.floor(tile(from).troops*state.deployment/100));if(tile(from).troops<2)return toast('This territory needs more troops.');attack(from,id,amount);state.selected=null;renderAll();update();checkVictory();}
    function attack(from,to,amount){const a=tile(from),d=tile(to);a.troops-=amount;if(d.owner==='player'){d.troops=Math.min(60,d.troops+amount);return;}const defense=d.troops+(d.owner==='neutral'?2:5);if(amount>defense){const old=d.owner;d.owner='player';d.troops=Math.max(2,amount-defense);d.city=false;state.score+=old==='bot'?120:35;state.food+=old==='bot'?8:3;addLog(`Captured ${to} from ${old==='bot'?'an enemy nation':'the frontier'}.`);setStatus(`Territory ${to} captured.`,'good');}else{d.troops=Math.max(1,defense-Math.floor(amount*.75));state.score+=5;setStatus('The attack failed to break the defense.','bad');}}
    function botTurn(){const own=owned('bot').filter(id=>tile(id).troops>=7);if(!own.length)return;for(let i=0;i<4;i++){const current=owned('bot').filter(id=>tile(id).troops>=7);if(!current.length)return;const from=current[Math.floor(Math.random()*current.length)],opts=neighbors(from),pt=opts.filter(id=>tile(id).owner==='player'),nt=opts.filter(id=>tile(id).owner==='neutral'),target=pt.length&&Math.random()<.5?pt[Math.floor(Math.random()*pt.length)]:nt[Math.floor(Math.random()*nt.length)]||pt[0];if(!target)continue;const amount=Math.max(1,Math.floor(tile(from).troops*.35)),a=tile(from),d=tile(target);a.troops-=amount;const defense=d.troops+(d.owner==='neutral'?2:5);if(amount>defense){const old=d.owner;d.owner='bot';d.troops=Math.max(2,amount-defense);d.city=false;if(old==='player'){state.score=Math.max(0,state.score-40);addLog(`Enemy forces captured ${target}.`);setStatus('An enemy attack captured one of your territories.','bad');}}else d.troops=Math.max(1,defense-Math.floor(amount*.7));}}
    function income(){const p=owned('player').length;state.gold+=p*.8+state.cities*2;state.food=Math.max(0,state.food+p*.45-state.cities*.15);state.science+=state.cities*.35;owned('player').forEach(id=>tile(id).troops=Math.min(60,tile(id).troops+(tile(id).city?2:1)));owned('bot').forEach(id=>tile(id).troops=Math.min(60,tile(id).troops+1));}
    function tick(){if(!state.active||state.paused)return;state.time++;state.turn++;if(state.turn%2===0)income();if(state.turn%3===0)botTurn();renderAll();update();checkVictory();}
    function checkVictory(){const p=owned('player').length,b=owned('bot').length;if(b===0||p>=80)endGame(true);else if(p===0)endGame(false);}
    function endGame(win){if(!state.active)return;state.active=false;clearInterval(state.loop);$('modalTitle').textContent=win?'Nation Victorious':'Nation Defeated';$('modalText').textContent=win?'Your nation secured the battlefield.':'Your territories were lost. Start another match and try a new strategy.';$('finalScore').textContent=Math.floor(state.score);$('finalTerritory').textContent=owned('player').length;$('finalTime').textContent=formatTime(state.time);$('finalCities').textContent=state.cities;el.modal.classList.add('show');}
    function applyCamera(){el.map.style.transform=`translate(${state.cameraX}px,${state.cameraY}px) scale(${state.zoom})`;}
    function centerMap(){const r=el.arena.getBoundingClientRect(),mw=state.size*64,mh=state.size*64;state.zoom=Math.min(1,Math.max(.65,Math.min((r.width-100)/mw,(r.height-120)/mh)));state.cameraX=(r.width-mw*state.zoom)/2;state.cameraY=(r.height-mh*state.zoom)/2;applyCamera();}
    function zoomAt(d,x,y){const old=state.zoom;state.zoom=Math.min(1.6,Math.max(.55,state.zoom+d));const ratio=state.zoom/old;state.cameraX=x-(x-state.cameraX)*ratio;state.cameraY=y-(y-state.cameraY)*ratio;applyCamera();}
    function startGame(){state.active=true;state.paused=false;state.time=0;state.score=0;state.turn=0;state.selected=null;state.gold=100;state.food=80;state.science=0;state.cities=1;state.zoom=1;state.cameraX=0;state.cameraY=0;state.buildMode=false;el.modal.classList.remove('show');el.log.innerHTML='';createMap();setupNations();centerMap();update();setStatus('Select one of your blue territories, then choose an adjacent territory.');clearInterval(state.loop);state.loop=setInterval(tick,1000);}
    $('menuBtn').onclick=()=>location.href='index.html';$('modalMenuBtn').onclick=()=>location.href='index.html';$('againBtn').onclick=startGame;$('pauseBtn').onclick=()=>{state.paused=!state.paused;setStatus(state.paused?'Game paused.':'Game resumed.');update();};$('centerBtn').onclick=centerMap;$('buildBtn').onclick=()=>{state.buildMode=!state.buildMode;state.selected=null;setStatus(state.buildMode?'Build mode: choose an empty territory you control.':'Build mode cancelled.');renderAll();};
    $('cityBtn').onclick=()=>{if(!state.selected)return toast('Select a territory first.');const t=tile(state.selected);if(t.owner!=='player'||t.city)return toast('Select an empty territory you control.');if(state.gold<40)return toast('You need 40 gold.');t.city=true;state.gold-=40;state.cities++;state.score+=75;addLog(`Founded a city at ${state.selected}.`);state.selected=null;renderAll();update();};
    $('researchBtn').onclick=()=>{if(state.gold<25)return toast('You need 25 gold.');state.gold-=25;state.science+=10;state.score+=30;addLog('Research investment completed.');toast('+10 science');update();};
    $('panelBtn').onclick=()=>el.side.classList.toggle('open');el.deploy.oninput=()=>{state.deployment=Number(el.deploy.value);el.deployValue.textContent=state.deployment;};
    el.arena.addEventListener('wheel',e=>{e.preventDefault();const r=el.arena.getBoundingClientRect();zoomAt(e.deltaY<0?.08:-.08,e.clientX-r.left,e.clientY-r.top);},{passive:false});
    el.arena.addEventListener('pointerdown',e=>{if(e.target.closest('.tile,.side,.hud,.topbar,.bottom'))return;state.dragging=true;state.dragX=e.clientX;state.dragY=e.clientY;state.startX=state.cameraX;state.startY=state.cameraY;el.arena.setPointerCapture(e.pointerId);});
    el.arena.addEventListener('pointermove',e=>{if(!state.dragging)return;state.cameraX=state.startX+e.clientX-state.dragX;state.cameraY=state.startY+e.clientY-state.dragY;applyCamera();});el.arena.addEventListener('pointerup',()=>state.dragging=false);el.arena.addEventListener('pointercancel',()=>state.dragging=false);
    window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='p')$('pauseBtn').click();if(e.key==='Escape'){state.selected=null;state.buildMode=false;renderAll();update();}});window.addEventListener('resize',centerMap);
    startGame();
  }
  function showBootError(error){console.error('Nation Wars failed to load:',error);const status=document.getElementById('status');if(status){status.textContent='Game failed to start. Refresh the page and try again.';status.className='status bad';}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{try{boot();}catch(e){showBootError(e);}});else{try{boot();}catch(e){showBootError(e);}}
})();
