(()=>{'use strict';
const SERVER='wss://nationwars.onrender.com/ws', $=id=>document.getElementById(id),mount=$('game');let T=window.THREE,scene,camera,renderer,ray,mouse,ws,state=null,myId=null,selected=null,drag=false,lx=0,ly=0,yaw=.15,pitch=.78,dist=34,retry=0;
function status(x){$('status').textContent=x}function fail(x){status(x)}
function start(){if(!T){fail('3D engine failed to load. Check your connection and refresh.');return}try{init()}catch(e){console.error(e);fail('3D multiplayer failed to start. Refresh the page.')}}
if(!T){status('Loading 3D engine…');let s=document.createElement('script');s.src='https://unpkg.com/three@0.160.0/build/three.min.js';s.onload=()=>{T=window.THREE;start()};s.onerror=()=>fail('Could not load the 3D engine.')}else start();
function init(){
 scene=new T.Scene();scene.background=new T.Color(0x07111d);scene.fog=new T.Fog(0x07111d,40,110);camera=new T.PerspectiveCamera(50,innerWidth/innerHeight,.1,180);renderer=new T.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.domElement.style.touchAction='none';mount.replaceChildren(renderer.domElement);ray=new T.Raycaster();mouse=new T.Vector2();scene.add(new T.HemisphereLight(0xbddcff,0x172313,2.1));let sun=new T.DirectionalLight(0xffffff,2.5);sun.position.set(20,35,10);scene.add(sun);events();cameraUpdate();connect();loop()}
 function connect(){if(ws&&ws.readyState===1)return;status(retry?'Reconnecting to multiplayer server…':'Connecting to multiplayer server…');try{ws=new WebSocket(SERVER)}catch(e){schedule();return}ws.onopen=()=>{retry=0;status('Connected. Create a room or join with a code.')};ws.onerror=()=>status('Server connection failed. Retrying…');ws.onclose=()=>{status('Disconnected. Retrying…');schedule()};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='error'){status(m.message||'Server error');return}if(m.type==='created'||m.type==='joined'){myId=m.you;$('roomOut').textContent=m.room;status('Room '+m.room+' ready. Share the code with the other player.')}if(m.type==='lobby'){$('roomOut').textContent=m.room;status(m.players.length+' player(s): '+m.players.map(p=>p.name+(p.ready?' ✓':'')).join(', '))}if(m.type==='start'||m.type==='state'){state=m.state||m;$('lobby').classList.add('hidden');draw();hud()}if(m.type==='gameOver'){state=m.final;draw();hud();$('help').innerHTML=m.winner===myId?'<span class="win">Victory! You control the winning nation.</span>':'The battle has ended.'}}}
 function schedule(){if(retry>6)return;retry++;setTimeout(connect,Math.min(8000,1500*retry))}function send(m){if(ws&&ws.readyState===1)ws.send(JSON.stringify(m));else status('Still connecting to the multiplayer server…')}
 function mapSize(){return state?Math.round(Math.sqrt(Object.keys(state.tiles||{}).length))||16:16}function pof(id,size){let [r,c]=id.split('-').map(Number),h=size/2;return new T.Vector3((c-h+.5)*2.5,0,(r-h+.5)*2.5)}
 function draw(){if(!state)return;scene.children.filter(o=>o.userData&&o.userData.mapObject).forEach(o=>scene.remove(o));let size=mapSize(),floor=new T.Mesh(new T.PlaneGeometry(size*2.5,size*2.5),new T.MeshLambertMaterial({color:0x21452f}));floor.rotation.x=-Math.PI/2;floor.userData.mapObject=true;floor.userData.ground=true;floor.userData.id='ground';scene.add(floor);let grid=new T.GridHelper(size*2.5,size,0x557b62,0x365342);grid.position.y=.02;grid.material.transparent=true;grid.material.opacity=.48;grid.userData.mapObject=true;scene.add(grid);
 Object.entries(state.tiles).forEach(([id,t])=>{let p=pof(id,size),pl=state.players.find(x=>x.id===t.owner),color=new T.Color(pl?pl.color:'#4b5a68');let tile=new T.Mesh(new T.BoxGeometry(2.28,.14,2.28),new T.MeshStandardMaterial({color,roughness:.85}));tile.position.set(p.x,.07,p.z);tile.userData={mapObject:true,id};scene.add(tile);if(t.troops>0){let g=new T.Group();g.position.set(p.x,0,p.z);g.userData={mapObject:true,id};let base=new T.Mesh(new T.CylinderGeometry(.48,.6,.2,8),new T.MeshStandardMaterial({color}));base.position.y=.2;g.add(base);for(let i=0;i<Math.min(9,Math.max(2,Math.ceil(t.troops/15)));i++){let u=new T.Mesh(new T.BoxGeometry(.22,.7,.22),new T.MeshStandardMaterial({color:0xe4edf5}));u.position.set((i%3-1)*.32,.57,(Math.floor(i/3)-1)*.32);g.add(u)}g.traverse(o=>{o.userData={mapObject:true,id}});scene.add(g)}});highlight()}
 function tileFrom(e){let r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);for(let h of ray.intersectObjects(scene.children,true))if(h.object.userData.id&&h.object.userData.id!=='ground')return h.object.userData.id;return null}
 function adjacent(a,b){let [ar,ac]=a.split('-').map(Number),[br,bc]=b.split('-').map(Number);if(Math.abs(ar-br)>1)return false;if(ar===br)return Math.abs(ac-bc)===1;let allowed=(ar%2===0)?[ac-1,ac]:[ac,ac+1];return Math.abs(ar-br)===1&&allowed.includes(bc)}
 function click(e){if(drag||!state)return;let id=tileFrom(e);if(!id)return;let t=state.tiles[id];if(t.owner===myId){selected=id;$('selected').textContent=`Selected territory ${id} · ${t.troops} troops`;$('help').textContent='Right-click an adjacent territory to move or attack.';highlight()}else if(selected)order(id)}
 function order(to){let from=selected,t=state.tiles[from];if(!t||t.owner!==myId)return;if(!adjacent(from,to)){$('help').textContent='That territory is not adjacent.';return}let amount=Math.max(1,Math.floor(t.troops*.6));send({type:'action',from,to,amount});$('help').textContent='Order sent. Waiting for server update.'}
 function highlight(){scene.children.filter(o=>o.userData&&o.userData.selection).forEach(o=>scene.remove(o));if(!selected)return;let id=selected,size=mapSize(),p=pof(id,size),r=new T.Mesh(new T.RingGeometry(.75,.93,24),new T.MeshBasicMaterial({color:0x72c5ff,side:T.DoubleSide,transparent:true,opacity:.95}));r.rotation.x=-Math.PI/2;r.position.set(p.x,.16,p.z);r.userData.selection=true;scene.add(r)}
 function hud(){if(!state)return;let mine=Object.values(state.tiles).filter(t=>t.owner===myId);$('territory').textContent=mine.length;$('troops').textContent=mine.reduce((s,t)=>s+t.troops,0);let sec=state.time||0;$('time').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');if(selected&&!state.tiles[selected]){selected=null;$('selected').textContent='Select one of your territories.'}}
 function cameraUpdate(){let h=Math.cos(pitch)*dist;camera.position.set(Math.sin(yaw)*h,Math.sin(pitch)*dist,Math.cos(yaw)*h);camera.lookAt(0,0,0)}
 function events(){
  $('create').onclick=()=>send({type:'create',name:$('name').value.trim()||'Commander',settings:{mapSize:24,gameLength:30}});$('join').onclick=()=>{let room=$('room').value.trim().toUpperCase();if(!room){status('Enter a room code first.');return}send({type:'join',name:$('name').value.trim()||'Commander',room})};$('ready').onclick=()=>send({type:'ready',ready:true});$('back').onclick=()=>{try{if(ws)ws.close()}catch{}location.href='index.html'};
  renderer.domElement.addEventListener('click',click);renderer.domElement.addEventListener('contextmenu',e=>{e.preventDefault();if(state&&selected){let id=tileFrom(e);if(id)order(id)}});
  renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===1||(e.button===0&&e.shiftKey)){drag=false;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)}});renderer.domElement.addEventListener('pointermove',e=>{if((e.buttons&4)||(e.buttons&1&&e.shiftKey)){let dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>3)drag=true;yaw-=dx*.006;pitch=Math.max(.48,Math.min(1.18,pitch+dy*.004));cameraUpdate();lx=e.clientX;ly=e.clientY}});renderer.domElement.addEventListener('wheel',e=>{dist=Math.max(17,Math.min(58,dist+e.deltaY*.025));cameraUpdate()},{passive:true});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
 function loop(){requestAnimationFrame(loop);renderer.render(scene,camera)}
} })();