(() => {
'use strict';
const SERVER='wss://nationwars.onrender.com/ws'; const mount=document.getElementById('game');
let scene,camera,renderer,ray,mouse,ws,state=null,myId=null,selected=null,meshes=new Map(),drag=false,lx=0,ly=0,yaw=0,dist=34,height=30;
const T=THREE, tile=2.5;
function pos(id,size){const [r,c]=id.split('-').map(Number),h=size/2;return new T.Vector3((c-h+.5)*tile,0,(r-h+.5)*tile)}
function init(){scene=new T.Scene();scene.background=new T.Color(0x07111d);scene.fog=new T.Fog(0x07111d,35,100);camera=new T.PerspectiveCamera(48,innerWidth/innerHeight,.1,160);renderer=new T.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;mount.appendChild(renderer.domElement);ray=new T.Raycaster();mouse=new T.Vector2();scene.add(new T.HemisphereLight(0xbddcff,0x1b261b,2));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(20,35,10);scene.add(sun);connect();events();loop();}
function connect(){ws=new WebSocket(SERVER);ws.onopen=()=>status('Connected. Create or join a room.');ws.onclose=()=>status('Disconnected from server. Refresh to reconnect.');ws.onerror=()=>status('Could not connect to multiplayer server.');ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='created'||m.type==='joined'){myId=m.you;document.getElementById('roomOut').textContent=m.room;status('Room '+m.room+' created/joined.')}if(m.type==='lobby'){document.getElementById('roomOut').textContent=m.room;status(m.players.length+' player(s): '+m.players.map(p=>p.name+(p.ready?' ✓':'')).join(', '))}if(m.type==='start'||m.type==='state'){state=m.state||m;document.getElementById('lobby').classList.add('hidden');draw();hud()}if(m.type==='gameOver'){state=m.final;draw();hud();document.getElementById('help').innerHTML=m.winner===myId?'<span class="win">Victory! You control the winning nation.</span>':'The battle has ended.'}}}
function status(x){document.getElementById('status').textContent=x}function send(x){if(ws&&ws.readyState===1)ws.send(JSON.stringify(x))}
function draw(){if(!state)return;scene.children.filter(o=>o.userData&&o.userData.mapObject).forEach(o=>scene.remove(o));meshes.clear();const size=Math.sqrt(Object.keys(state.tiles).length)||16;const floor=new T.Mesh(new T.PlaneGeometry(size*tile,size*tile),new T.MeshLambertMaterial({color:0x1b3a2a}));floor.rotation.x=-Math.PI/2;floor.userData.mapObject=true;floor.userData.id='ground';scene.add(floor);const line=new T.GridHelper(size*tile,size,0x496d55,0x304b3a);line.position.y=.02;line.userData.mapObject=true;scene.add(line);Object.entries(state.tiles).forEach(([id,t])=>{const p=pos(id,size);const color=t.owner?new T.Color((state.players.find(x=>x.id===t.owner)||{}).color||'#64748b'):new T.Color('#34495e');const tileMesh=new T.Mesh(new T.BoxGeometry(tile*.9,.12,tile*.9),new T.MeshLambertMaterial({color}));tileMesh.position.set(p.x,.06,p.z);tileMesh.userData={mapObject:true,id};scene.add(tileMesh);if(t.troops>0){const g=new T.Group();g.position.set(p.x,0,p.z);g.userData={mapObject:true,id};const base=new T.Mesh(new T.CylinderGeometry(.45,.58,.18,8),new T.MeshLambertMaterial({color}));base.position.y=.2;g.add(base);for(let i=0;i<Math.min(7,Math.max(2,Math.ceil(t.troops/18)));i++){const u=new T.Mesh(new T.BoxGeometry(.2,.65,.2),new T.MeshLambertMaterial({color:0xe2edf5}));u.position.set((i%3-.9)*.3,(.55),(Math.floor(i/3)-.5)*.3);g.add(u)}g.traverse(o=>o.userData={mapObject:true,id});scene.add(g);meshes.set(id,g)}});}
function tileFromEvent(e){const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(scene.children,true);for(const h of hits)if(h.object.userData.id&&h.object.userData.id!=='ground')return h.object.userData.id;return null}
function click(e){if(drag)return;const id=tileFromEvent(e);if(!id||!state)return;const t=state.tiles[id];if(t.owner===myId){selected=id;document.getElementById('selected').textContent=`Selected territory ${id} · ${t.troops} troops`;highlight()}else if(selected)order(id)}
function adjacent(a,b){const [ar,ac]=a.split('-').map(Number),[br,bc]=b.split('-').map(Number);if(Math.abs(ar-br)>1)return false;if(ar===br)return Math.abs(ac-bc)===1;const allowed=(ar%2===0)?[ac-1,ac]:[ac,ac+1];return Math.abs(ar-br)===1&&allowed.includes(bc)}
function order(to){const from=selected,t=state.tiles[from];if(!t||t.owner!==myId)return;if(!adjacent(from,to)){document.getElementById('help').textContent='That territory is not adjacent.';return}const amount=Math.max(1,Math.floor(t.troops*.6));send({type:'action',from,to,amount});document.getElementById('help').textContent='Order sent to server.'}
function highlight(){if(!selected||!meshes.has(selected))return;const g=meshes.get(selected);if(g.getObjectByName('selection'))return;const r=new T.Mesh(new T.RingGeometry(.65,.78,24),new T.MeshBasicMaterial({color:0x55b7ff,side:T.DoubleSide}));r.name='selection';r.rotation.x=-Math.PI/2;r.position.y=.15;g.add(r)}
function hud(){if(!state)return;const mine=Object.values(state.tiles).filter(t=>t.owner===myId);document.getElementById('territory').textContent=mine.length;document.getElementById('troops').textContent=mine.reduce((s,t)=>s+t.troops,0);const sec=state.time||0;document.getElementById('time').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function cameraUpdate(){camera.position.set(Math.sin(yaw)*dist,height,Math.cos(yaw)*dist);camera.lookAt(0,0,0)}
function events(){document.getElementById('create').onclick=()=>{const name=document.getElementById('name').value.trim()||'Commander';send({type:'create',name,settings:{mapSize:24,gameLength:30}})};document.getElementById('join').onclick=()=>{const name=document.getElementById('name').value.trim()||'Commander',room=document.getElementById('room').value.trim().toUpperCase();if(!room)return status('Enter a room code first.');send({type:'join',name,room})};document.getElementById('ready').onclick=()=>send({type:'ready',ready:true});document.getElementById('back').onclick=()=>location.href='index.html';renderer.domElement.addEventListener('click',click);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{drag=false;lx=e.clientX;ly=e.clientY});renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons===1){const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>5)drag=true;yaw-=dx*.005;height=Math.max(15,Math.min(55,height+dy*.08));cameraUpdate();lx=e.clientX;ly=e.clientY}});renderer.domElement.addEventListener('wheel',e=>{dist=Math.max(18,Math.min(55,dist+e.deltaY*.025));cameraUpdate()},{passive:true});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});cameraUpdate()}
function loop(){requestAnimationFrame(loop);renderer.render(scene,camera)}init();
})();